<?php
/**
 * @file
 * Build page and form for internet reception.
 */

/**
 * Implements hook_menu().
 */
function online_reception_menu() {
  $items = array();
  $items['online_reception_page'] = array(
    'title' => 'Online reception',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('online_reception_form'),
    'access callback' => 'user_is_logged_in',
    'menu_name' => 'main-menu'
  );
  return $items;
}

/**
 * Build internet reception form.
 */
function online_reception_form($form, $form_state) {
  $form = array();
  $form['last-name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['middle-name'] = array(
    '#type' => 'textfield',
    '#title' => t('Middle name'),
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['age'] = array(
    '#type' => 'textfield',
    '#title' => t('Age'),
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['topic-appeal'] = array(
    '#type' => 'textfield',
    '#title' => t('Topic appeal'),
    '#maxlength' => 255,
    '#required' => TRUE,
  );
  $form['text-of-the-appeal'] = array(
    '#type' => 'textarea',
    '#title' => t('Text of the appeal'),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

/**
 * Validate function for internet_reception_form.
 */
function online_reception_form_validate($form, &$form_state) {
  if (!is_numeric($form_state['values']['age'])) {
    form_set_error('age', t('The "Age" must be numeric'));
  }
  if ($form_state['values']['age'] <= 0) {
    form_set_error('age', t('The "Age" should not be negative.'));
  }
}

/**
 * Submit function for internet_reception_form.
 */
function online_reception_form_submit($form, &$form_state) {
  global $user;
  $module = 'internet_reception';
  $key = 'key';
  $language = 'ru';
  $params = array();
  $from = $user->mail;
  $send = FALSE;
  $message = drupal_mail($module, $key, variable_get('site_mail'),
    $language, $params, $from, $send); // формируем сообщение
  $message['subject'] = 'Request online reception';
  $message['body'] = array();
  $message['body'][] = "Last name: " . $form_state['values']['last-name'] . "\n"
    . "Name: " . $form_state['values']['name'] . "\n"
    . "Middle name: " . $form_state['values']['middle-name'] . "\n"
    . "Age: " . $form_state['values']['age'] . "\n"
    . "Topic appeal: " . $form_state['values']['topic-appeal'] . "\n"
    . "Text of the appeal: " . $form_state['values']['text-of-the-appeal'];
  $system = drupal_mail_system($module, $key);
  $message = $system->format($message);
  $message['result'] = $system->mail($message);
}